export enum TechGroup {
    WESTERN,
    EASTERN,
    ANATOLIAN,
    MUSLIM,
    NOMADIC,
    AFRICAN,
    CHINESE,
    INDIAN,
    NORTH_AMERICAN,
    MESOAMERICAN,
    SOUTH_AMERICAN,
    HIGH_AMERICAN,
    ABORIGINAL,
    POLYNESIAN,
    NONE
}